### ISSUE TITLE
Error when using inside Rails Engine

### ISSUE THREAD

**Issue by plagi** [ndea/regressor#9]
% bundle exec rails generate regressor:model                                          1 ↵ ✹ ✭
/Users/plagi/.rvm/gems/ruby-2.1.2@leadhacker/gems/regressor-0.4.0/lib/generators/regressor/model_generator.rb:8:in `create_regression_files': undefined method`eager_load!' for nil:NilClass (NoMethodError)
    from /Users/plagi/.rvm/gems/ruby-2.1.2@leadhacker/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/plagi/.rvm/gems/ruby-2.1.2@leadhacker/gems/thor-0.19.1/lib/thor/invocation.rb:126:in`invoke_command'
    from /Users/plagi/.rvm/gems/ruby-2.1.2@leadhacker/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    from /Users/plagi/.rvm/gems/ruby-2.1.2@leadhacker/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`each'
    from /Users/plagi/.rvm/gems/ruby-2.1.2@leadhacker/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
    from /Users/plagi/.rvm/gems/ruby-2.1.2@leadhacker/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`invoke_all'
    from /Users/plagi/.rvm/gems/ruby-2.1.2@leadhacker/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
    from /Users/plagi/.rvm/gems/ruby-2.1.2@leadhacker/gems/thor-0.19.1/lib/thor/base.rb:440:in`start'
    from /Users/plagi/.rvm/gems/ruby-2.1.2@leadhacker/gems/railties-4.1.10/lib/rails/generators.rb:157:in `invoke'
    from /Users/plagi/.rvm/gems/ruby-2.1.2@leadhacker/gems/railties-4.1.10/lib/rails/commands/generate.rb:11:in`<top (required)>'
    from /Users/plagi/.rvm/gems/ruby-2.1.2@leadhacker/gems/railties-4.1.10/lib/rails/engine/commands.rb:19:in `require'
    from /Users/plagi/.rvm/gems/ruby-2.1.2@leadhacker/gems/railties-4.1.10/lib/rails/engine/commands.rb:19:in`<top (required)>'
    from bin/rails:12:in `require'
    from bin/rails:12:in`<main>'

**Comment by erwinjunker** [comment]
Hi plagi, can you say which rails version do you use? That looks pretty strange. Can you test the following command in the rails console?

``` ruby
Rails.application.eager_load!
```

**Comment by plagi** [comment]
Hey,

This happens when developing inside rails engine. 
Rails version 4.2.12

С уважением, 
Алексей

**Comment by artschie1337** [comment]
Do you use ActiveRecord or Mongoid?

**Comment by plagi** [comment]
active_record

С уважением, 
Алексей
